'use strict';
const DATA=JSON.parse(document.getElementById('guide-data').textContent);
const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>Array.from(root.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=new Map(DATA.articles.map(a=>[a.id,a]));
const categoryMap=new Map(DATA.categories.map((c,i)=>[c.id,{...c,index:i+1}]));
const icon=(n)=>{const paths={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4z"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',coin:'<circle cx="12" cy="12" r="9"/><path d="m8 7 4 5 4-5M8 12h8M8 15h8M12 12v6"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',rows:'<path d="M8 5h13M8 12h13M8 19h13M3 5h.1M3 12h.1M3 19h.1"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',moon:'<path d="M20 14A8 8 0 0 1 10 4 8 8 0 1 0 20 14Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M5 19l1-1M18 6l1-1"/>',book:'<path d="M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Zm0 0v16"/>',print:'<path d="M6 8V3h12v5M6 17H3V9h18v8h-3"/><path d="M6 14h12v7H6zM17 11h1"/>',link:'<path d="m10 13 4-4m-6 6-2 2a3 3 0 0 1-4-4l5-5a3 3 0 0 1 4 0m2 3a3 3 0 0 0 4 0l5-5a3 3 0 0 0-4-4l-2 2"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.book}</svg>`;};
let storageOK=true;
function readState(){try{const raw=JSON.parse(localStorage.getItem('kurashi-notebook-v1')||'{}');return sanitizeNotebook(raw);}catch{return {bookmarks:[],done:[],notes:{}};}}
function sanitizeNotebook(raw){if(!raw||typeof raw!=='object')raw={};const validIds=arr=>Array.isArray(arr)?[...new Set(arr.filter(id=>typeof id==='string'&&byId.has(id)))]:[];const notes={};if(raw.notes&&typeof raw.notes==='object')for(const [id,value] of Object.entries(raw.notes)){if(byId.has(id)&&typeof value==='string')notes[id]=value.slice(0,2000);}return {bookmarks:validIds(raw.bookmarks),done:validIds(raw.done),notes};}
let notebook=readState();
let state={view:'explore',category:'',query:'',cost:'',time:'',evidence:'',audience:'',sort:'priority',limit:18,layout:'cards',saved:'bookmarks'};
const audienceGroups={'働く・仕事を探す':/働|仕事|会社員|職|パート|アルバイト|雇用/,'子育て・妊娠':/子育て|こども|子ども|乳幼児|妊娠|出産|育児|保育|養育/,'高齢・介護':/高齢|介護|年金|金銭管理|相続|葬儀|遺言/,'住まい・引越し':/住まい|住宅|引越|家賃|家財/,'家計・税・年金':/家計|控除|申告|納税|年金|保険|借入|返済|生活費|資産|カード/,'事業・フリーランス':/事業|創業|開業|副業|フリーランス|発注/,'治療・服薬中':/医療|治療|薬|通院|入院|病気|療養/,'学生・学び直し':/学生|学び|資格|進路|就職活動|通学/};
let currentArticle=null,toastTimer,searchTimer;
function persist(){try{localStorage.setItem('kurashi-notebook-v1',JSON.stringify(notebook));storageOK=true;}catch{storageOK=false;toast('この環境では記録を保存できません。書き出して保管してください。');}updateCounts();}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function normalize(s){return s.normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96));}
function articleSearchText(a){return normalize([a.title,a.summary,a.benefit,categoryMap.get(a.category)?.title,...a.tags,...a.steps,...a.audience,...a.cautions,...a.sources.flatMap(s=>[s.title,s.publisher])].join(' '));}
const searchIndex=new Map(DATA.articles.map(a=>[a.id,articleSearchText(a)]));
function filtered(){const terms=normalize(state.query.trim()).split(/[\s　]+/).filter(Boolean);const result=DATA.articles.filter(a=>(!state.category||a.category===state.category)&&(!state.cost||a.cost===state.cost)&&(!state.time||a.time===state.time)&&(!state.evidence||a.evidence===state.evidence)&&(!state.audience||a.audience.includes('すべての人')||audienceGroups[state.audience]?.test(a.audience.join(' ')))&&terms.every(term=>searchIndex.get(a.id).includes(term)));const order={"5分":0,"15分":1,"30分":2,"継続":3};result.sort((a,b)=>state.sort==='chapter'?categoryMap.get(a.category).index-categoryMap.get(b.category).index||a.id.localeCompare(b.id):state.sort==='time'?(order[a.time]-order[b.time])||a.priority-b.priority:a.priority-b.priority||Number(a.id.split('-').pop())-Number(b.id.split('-').pop())||categoryMap.get(a.category).index-categoryMap.get(b.category).index);return result;}
function card(a){const saved=notebook.bookmarks.includes(a.id),done=notebook.done.includes(a.id);return `<article class="article-card"><div class="card-top"><span class="category-chip">${esc(categoryMap.get(a.category).title)}</span><button class="bookmark-button" data-bookmark="${a.id}" aria-pressed="${saved}" aria-label="${esc(a.title)}を${saved?'保存から外す':'あとで読むに保存'}">${icon('bookmark')}</button></div><h3><button class="card-title" data-article="${a.id}">${esc(a.title)}</button></h3><p class="card-summary">${esc(a.summary)}</p><div class="card-meta"><span>${icon('coin')}${esc(a.cost)}</span><span>${icon('clock')}${a.category==='emergency'?'平時の準備 ':''}${esc(a.time)}</span>${done?'<span class="done-badge">✓ できた</span>':''}</div><div class="card-bottom"><span class="evidence">${esc(a.evidence)}</span><button data-article="${a.id}">手順を読む <span aria-hidden="true">↗</span></button></div></article>`;}
function empty(title,description,reset=false){return `<div class="empty-state">${icon('book')}<h3>${esc(title)}</h3><p>${esc(description)}</p>${reset?'<button class="outline-button" data-reset>条件をリセット</button>':'<button class="outline-button" data-view="explore">ガイドを探す</button>'}</div>`;}
function buildSidebar(){const groups=DATA.groups;$('#chapter-nav').innerHTML=groups.map(g=>`<details class="chapter-group"><summary>${g.title}</summary>${g.ids.filter(id=>categoryMap.has(id)).map(id=>{const c=categoryMap.get(id);return `<button class="chapter-button" data-category="${c.id}"><span class="chapter-index">${String(c.index).padStart(2,'0')}</span><span class="chapter-name">${esc(c.title)}</span><span class="chapter-count">${DATA.articles.filter(a=>a.category===c.id).length}</span></button>`;}).join('')}</details>`).join('');$('#all-count').textContent=DATA.articles.length;$('#chapter-total').textContent=DATA.categories.length+'テーマ';$('#hero-count').textContent=DATA.articles.length;$('#hero-chapters').textContent=DATA.categories.length;$('.book-num').textContent='01 — '+DATA.categories.length;$('#revision-date').textContent=DATA.updated.replaceAll('-','.');$('#audience-filter').innerHTML+=Object.keys(audienceGroups).map(a=>`<option>${esc(a)}</option>`).join('');}
function renderExplore(){const list=filtered(),cat=categoryMap.get(state.category);$('#section-title').textContent=cat?cat.title:'いま、気になることは？';$('#section-kicker').textContent=cat?'第'+String(cat.index).padStart(2,'0')+'章':'暮らしのガイド';$('#section-description').textContent=cat?cat.description:'知っておきたいことを、暮らしのテーマから。';$('#result-count').innerHTML=`<b>${list.length}</b>件のガイド <span>／ 全${DATA.articles.length}件</span>`;$('#article-grid').classList.toggle('rows',state.layout==='rows');$('#article-grid').innerHTML=list.length?list.slice(0,state.limit).map(card).join(''):empty('該当するガイドがありません','キーワードを短くするか、絞り込み条件を減らしてみてください。',true);$('#load-more').hidden=list.length<=state.limit;$('#load-more').innerHTML=`もっと読む <span>↓</span> <small>残り ${Math.max(0,list.length-state.limit)} 件</small>`;const filters=['cost','time','evidence','audience'].filter(k=>state[k]);$('#filter-number').textContent=filters.length?`(${filters.length})`:'';$('#active-filters').innerHTML=filters.map(k=>`<button data-remove-filter="${k}">${esc(state[k])} ×</button>`).join('');$$('[data-category]').forEach(el=>{const selected=el.dataset.category===state.category;el.classList.toggle('selected',selected);el.setAttribute('aria-current',selected?'page':'false');});$('#all-button').classList.toggle('selected',!state.category);$('#hero').hidden=!!cat;$('#quick-strip').hidden=!!cat;$('#start-bar').hidden=state.view!=='explore'||!!cat;$('#feature-teaser').hidden=state.view!=='explore'||!!cat;}
function renderJourneys(){$('#journey-grid').innerHTML=DATA.journeys.map((j,i)=>`<button class="journey-card" data-journey="${j.id}"><span class="journey-number">${String(i+1).padStart(2,'0')}</span><span class="journey-arrow">↗</span><h3>${esc(j.title)}</h3><p>${esc(j.description)}</p><small>${j.articleIds.length}件のガイドを、行動の順に</small></button>`).join('');}
function renderSaved(){const list=notebook[state.saved].map(id=>byId.get(id)).filter(Boolean);$('#notebook-stats').innerHTML=`<div class="stat"><b>${notebook.bookmarks.length}</b><span>あとで読む</span></div><div class="stat"><b>${notebook.done.length}</b><span>できたこと</span></div><div class="stat"><b>${Object.values(notebook.notes).filter(v=>v.trim()).length}</b><span>自分のメモ</span></div>`;$('#saved-grid').innerHTML=list.length?list.map(card).join(''):empty(state.saved==='done'?'小さな一歩から、はじめよう。':'気になる一歩を、ここに。',state.saved==='done'?'ガイドを読んで実行できたら「できた」にチェック。':'ガイドのしおりボタンを押すと、ここに保存されます。');$$('[data-saved]').forEach(b=>b.classList.toggle('active',b.dataset.saved===state.saved));}
function updateCounts(){$('#saved-count').textContent=notebook.bookmarks.length;}
function setView(view,scroll=true){state.view=view;$('#explore-panel').hidden=view!=='explore';$('#journeys-panel').hidden=view!=='journeys';$('#saved-panel').hidden=view!=='saved';$('#hero').hidden=view!=='explore'||!!state.category;$('#quick-strip').hidden=view!=='explore'||!!state.category;$('#start-bar').hidden=view!=='explore'||!!state.category;$('#feature-teaser').hidden=view!=='explore'||!!state.category;$$('.top-nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='explore')renderExplore();if(view==='saved')renderSaved();if(view==='journeys')renderJourneys();closeMenu();if(scroll)window.scrollTo({top:0,behavior:'auto'});}
function clearFilters(){Object.assign(state,{category:'',query:'',cost:'',time:'',evidence:'',audience:'',sort:'priority',limit:18});$('#search').value='';['cost','time','evidence','audience'].forEach(k=>$('#'+k+'-filter').value='');$('#sort-filter').value='priority';setView('explore',false);}
function toggleBookmark(id){const index=notebook.bookmarks.indexOf(id);if(index<0)notebook.bookmarks.push(id);else notebook.bookmarks.splice(index,1);persist();if(storageOK)toast(index<0?'あとで読むに保存しました':'保存から外しました');refreshLists();updateDetailButtons();}
function toggleDone(id){const index=notebook.done.indexOf(id);if(index<0)notebook.done.push(id);else notebook.done.splice(index,1);persist();showDailyStep();if(storageOK)toast(index<0?'「できたこと」に記録しました':'完了の記録を外しました');refreshLists();updateDetailButtons();}
function refreshLists(){renderExplore();if(state.view==='saved')renderSaved();$('#hero').hidden=state.view!=='explore'||!!state.category;$('#quick-strip').hidden=state.view!=='explore'||!!state.category;}
function showDialog(eyebrow,html){$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-content').innerHTML=html;if(!$('#detail-dialog').open)$('#detail-dialog').showModal();$('#detail-dialog').scrollTop=0;}
function sourceHTML(s){return `<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><small>${esc(s.publisher)} · ${esc(new URL(s.url).hostname)}</small></li>`;}
function openArticle(id,history=true){const a=byId.get(id);if(!a)return;currentArticle=id;const c=categoryMap.get(a.category),siblings=DATA.articles.filter(x=>x.category===a.category),index=siblings.findIndex(x=>x.id===id);const related=siblings.filter(x=>x.id!==id).slice(0,3);showDialog(`第${String(c.index).padStart(2,'0')}章　${c.title}`,`<span class="evidence">${esc(a.evidence)} · 原資料へのリンクあり</span><h2 class="detail-title">${esc(a.title)}</h2><p class="detail-summary">${esc(a.summary)}</p>${a.category==='emergency'?'<div class="urgent-note">いま生命の危険があるときは <a href="tel:119">119</a>。読むことを優先せず、指令員の案内に従ってください。以下の時間は平時の準備の目安です。</div>':''}<div class="detail-actions"><button id="detail-bookmark" data-bookmark="${id}"></button><button id="detail-done" data-done="${id}"></button><button data-copy="${id}">${icon('link')}リンク</button><button data-share="${id}">共有</button><button data-sharecard="${id}">画像カード ↓</button><button data-print="${id}">${icon('print')}印刷</button></div><dl class="detail-facts"><div><dt>費用の目安</dt><dd>${esc(a.cost)}</dd></div><div><dt>${a.category==='emergency'?'平時の準備の目安':'取りかかる時間の目安'}</dt><dd>${esc(a.time)}</dd></div><div><dt>対象の目安</dt><dd>${a.audience.map(esc).join('・')}</dd></div></dl><section class="detail-section"><h3>この一歩で、変えられること</h3><p>${esc(a.benefit)}</p></section><section class="detail-section"><h3>やること、順番に。</h3><ol class="steps">${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section class="detail-section cautions"><h3>先に確かめたいこと</h3><ul>${a.cautions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section><section class="detail-section"><h3>根拠・公式の確認先</h3><ul class="source-list">${a.sources.map(sourceHTML).join('')}</ul><p class="checked-note">内容確認日：${esc(a.checked)}。金額・期限・対象要件は、申請時に原資料と窓口で確認してください。所要時間と表示順は編集上の目安です。</p></section><section class="detail-section"><h3>自分用メモ</h3><textarea class="local-note" id="article-note" maxlength="2000" aria-label="自分用メモ" placeholder="確認したこと、次にやること。端末内だけに保存します。">${esc(notebook.notes[id]||'')}</textarea><small class="checked-note">入力すると保存されます。外部には送信されません。</small></section><section class="detail-section"><h3>同じテーマのガイド</h3><div class="related-links">${related.map(x=>`<button data-article="${x.id}">${esc(x.title)} ↗</button>`).join('')}</div></section><div class="article-navigation"><button ${index===0?'disabled':''} data-article="${siblings[index-1]?.id||id}">← 前のガイド</button><span class="chapter-progress">${index+1} / ${siblings.length}</span><button ${index===siblings.length-1?'disabled':''} data-article="${siblings[index+1]?.id||id}">次のガイド →</button></div>`);updateDetailButtons();$('#article-note').addEventListener('input',e=>{notebook.notes[id]=e.target.value;persist();});if(history)window.history.replaceState(null,'','#guide/'+id);}
function updateDetailButtons(){if(!currentArticle||!$('#detail-bookmark'))return;const saved=notebook.bookmarks.includes(currentArticle),done=notebook.done.includes(currentArticle);$('#detail-bookmark').innerHTML=icon('bookmark')+(saved?'保存済み':'あとで読む');$('#detail-bookmark').classList.toggle('active',saved);$('#detail-bookmark').setAttribute('aria-pressed',String(saved));$('#detail-done').innerHTML=icon('check')+(done?'できた':'できたにする');$('#detail-done').classList.toggle('active',done);$('#detail-done').setAttribute('aria-pressed',String(done));}
function openJourney(id){const j=DATA.journeys.find(j=>j.id===id);if(!j)return;currentArticle=null;showDialog('場面から選ぶ',`<div class="prose"><h2>${esc(j.title)}</h2><p>${esc(j.description)}</p><ol class="steps">${j.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="journey-articles">${j.articleIds.map((id,i)=>{const a=byId.get(id);return `<button data-article="${a.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(a.title)}${icon('arrow')}</button>`;}).join('')}</div><p class="checked-note" style="margin-top:25px">行動順は編集提案です。個別の事情や、窓口の案内を優先してください。</p></div>`);}
const editorial=`<div class="prose"><span class="eyebrow">編集方針</span><h2>選ぶための、判断帖。</h2><p>このガイドは、日本で暮らす人が、健康・お金・時間・家族を大切にするための実践集です。すべてを実行する必要はありません。いま必要な一歩を、原資料と照らし合わせて選ぶために作りました。</p><h3>「根拠」と「おすすめ順」を混ぜません</h3><table><tr><th>公的制度</th><td>法律・給付・公的サービスなどの公式説明を根拠にしています。受給や適用を保証する意味ではありません。</td></tr><tr><th>公的推奨</th><td>公的機関が案内する健康・安全・消費生活などの推奨です。効果の大きさや個人への適合を等級化したものではありません。</td></tr><tr><th>編集提案</th><td>公式情報をもとに組み立てた整理方法・行動順です。科学的な効果判定ではありません。</td></tr></table><h3>費用と時間の読み方</h3><p>「無料」は、主に調べる・記録する・相談を始める段階を指します。通話料・交通費・その後の購入や受診費用がかかる場合があります。「5分」「15分」「30分」は取りかかる作業の編集上の目安で、審査や手続きの完了時間ではありません。「継続」は習慣化や定期的な確認が必要な行動です。</p><p>おすすめ順は、取りかかりやすさ・見落としやすさ・暮らしへの影響をもとにした編集判断です。命・お金・権利を同じ点数に換算しません。</p><h3>確認したことと、残る確認</h3><p>記事には、公的機関を中心とした日本の一次資料へのリンクと内容確認日を付けています。第2版はAIを使って調査・編集したものです。独立した専門家による全件監修はまだ行っていません。確認日は、その後の制度変更やリンク先の更新を保証しません。</p><p>金額・要件が変わりやすい事項は、具体的な確認先と手順を重視しています。自治体・加入保険・家族構成などで扱いが違うため、手続き前に公式窓口で自分の条件を確認してください。医療・税務・法律の個別判断は専門職へ相談してください。</p><h3>困っているときは、読むより先に。</h3><p>生命に危険がある救急・火災は119、事件・事故の緊急通報は110へ。ウェブサイトを読み終えることを優先しないでください。地域の相談先は各記事の公式リンクから確認できます。</p><h3>あなたの記録は、あなたの端末に。</h3><p>しおり・完了・メモはブラウザーの保存領域に記録します。登録や外部送信はなく、端末間の自動同期もありません。共有端末ではメモの内容に気を配り、必要に応じて記録を書き出してください。</p><h3>修正・更新について</h3><p>本書は第2版です。公式情報の自動監視は行っていません。再公開時には原資料を見直し、確認日と変更履歴を更新する方針です。GitHub用の配布一式には、出典一覧・確認方針・変更提案用テンプレートを含めています。</p></div>`;
function showEditorial(){currentArticle=null;showDialog('このガイドについて',editorial);}
function showSources(){currentArticle=null;const sources=new Map();DATA.articles.forEach(a=>a.sources.forEach(s=>{if(!sources.has(s.url))sources.set(s.url,{...s,ids:[]});sources.get(s.url).ids.push(a.id);}));showDialog('出典一覧',`<div class="prose"><h2>根拠に、たどり着ける。</h2><p>${DATA.articles.length}件のガイドが参照する${sources.size}件の原資料。以下はこの第2版で確認した資料です。参照した原資料と、当ガイドの編集判断を区別してお読みください。</p><ul class="source-list">${[...sources.values()].sort((a,b)=>a.publisher.localeCompare(b.publisher,'ja')).map(s=>sourceHTML(s)).join('')}</ul></div>`);}
function showCredits(){currentArticle=null;showDialog('制作・ライセンス',`<div class="prose"><h2>くらしの判断帖</h2><p>日本で暮らす人のための、根拠と手順が見える生活ガイド。第2版 ${DATA.updated.replaceAll('-','.')}。</p><h3>制作について</h3><p>企画：Gerry。調査・構成・本文・実装：AIを用いた制作。日本の原資料をもとに書いた独自の日本語ガイドです。政府機関の公式サイトではありません。</p><h3>着想元への謝辞</h3><p>コスト・便益・根拠を並べて生活の判断を助ける構成は、eternity4719 氏の<a href="https://github.com/eternity4719/HowToLiveBetter" target="_blank" rel="noopener">HowToLiveBetter</a>から着想を得ています。原文・プログラムの複製や翻訳ではなく、日本の公的機関などの一次資料から再構成しました。原プロジェクトの本文は<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>で公開されています。</p><h3>この配布物のライセンス</h3><p>独自本文はCC BY 4.0、独自コードはMITで配布します。出典となる公式文書の権利や利用条件は、それぞれの発行元に帰属します。詳細はGitHub用ファイルのLICENSE-CONTENTとLICENSE-CODEを参照してください。</p><h3>オフラインでも読めます</h3><p>「オフライン版を保存」で、全文と検索機能が入ったHTMLを保存できます。端末のブラウザーで開いてください。リンク先の閲覧は通信が必要です。保存した版は自動更新されません。</p></div>`);}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function offlineDownload(){try{if(location.protocol==='file:'){toast('このHTMLがオフライン版です。ファイルをコピーして保管できます。');return;}const r=await fetch('./kurashi-offline.html');if(!r.ok)throw Error();download('くらしの判断帖-'+DATA.updated+'.html',await r.text(),'text/html;charset=utf-8');toast('オフライン版を保存しました');}catch{toast('保存に失敗しました。接続を確認して、もう一度お試しください。');}}
function exportNotebook(){download('くらしの判断帖-マイリスト.json',JSON.stringify({format:'kurashi-notebook',version:1,exportedAt:new Date().toISOString(),...notebook},null,2),'application/json');toast('記録を書き出しました');}
async function importNotebook(file){if(!file)return;try{if(file.size>8*1024*1024)throw Error();const raw=JSON.parse(await file.text());if(raw.format!=='kurashi-notebook'||raw.version!==1||!Array.isArray(raw.bookmarks)||!Array.isArray(raw.done))throw Error();const data=sanitizeNotebook(raw);notebook.bookmarks=[...new Set([...notebook.bookmarks,...data.bookmarks])];notebook.done=[...new Set([...notebook.done,...data.done])];notebook.notes={...data.notes,...notebook.notes};persist();renderSaved();refreshLists();if(storageOK)toast('記録を追加しました。既存のメモは保持しています。');}catch{toast('読み込めませんでした。このガイドから書き出したJSONを選んでください。');}$('#import-file').value='';}
function printArticles(articles,title){if(!articles.length){toast('印刷するガイドがありません');return;}let lastCat='';const cover=`<section class="print-cover"><h1>くらしの判断帖</h1><h2>${esc(title)}</h2><p>知って、選んで、少しよく。</p><p>内容確認日：${DATA.updated} · ${articles.length}件</p><p>日本の公的機関などの一次資料をもとにAIで調査・編集した第2版です。専門家による全件監修は未実施です。費用・所要時間・おすすめ順は編集上の目安です。制度の適用条件は、申請時に原資料と窓口で確認してください。</p><p>本文：CC BY 4.0 · 独自コード：MIT</p></section>`;$('#print-area').innerHTML=cover+articles.map(a=>{let heading='';if(lastCat!==a.category){lastCat=a.category;heading=`<h2 class="print-chapter">${esc(categoryMap.get(a.category).title)}</h2>`;}return heading+`<article class="print-article"><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><p>費用：${esc(a.cost)} / 時間：${esc(a.time)} / 根拠：${esc(a.evidence)} / 対象：${a.audience.map(esc).join('・')}</p><h4>期待できること</h4><p>${esc(a.benefit)}</p><h4>やること、順番に</h4><ol>${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h4>先に確かめたいこと</h4><ul>${a.cautions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><h4>根拠・公式の確認先</h4>${a.sources.map(s=>`<p class="print-source">${esc(s.publisher)}「${esc(s.title)}」<br>${esc(s.url)}</p>`).join('')}<p>内容確認日：${esc(a.checked)}</p></article>`;}).join('');window.print();}
async function copyLink(id){const url=DATA.siteUrl+'guide/'+encodeURIComponent(id)+'.html';try{await navigator.clipboard.writeText(url);toast('このガイドへのリンクをコピーしました');}catch{toast('アドレス欄のURLをコピーすると、このガイドを共有できます');}}
function closeMenu(){$('#sidebar').classList.remove('open');$('#sidebar-shade').classList.remove('open');$('#menu-button').setAttribute('aria-expanded','false');}
function setTheme(dark){document.documentElement.dataset.theme=dark?'dark':'light';$('#theme-button').innerHTML=icon(dark?'sun':'moon');$('#theme-button').setAttribute('aria-label',dark?'明るい配色にする':'暗い配色にする');try{localStorage.setItem('kurashi-theme',dark?'dark':'light');}catch{}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.article)openArticle(b.dataset.article);else if(b.dataset.bookmark)toggleBookmark(b.dataset.bookmark);else if(b.dataset.done)toggleDone(b.dataset.done);else if(b.dataset.view){if(b.dataset.view==='explore')state.category='';setView(b.dataset.view);}else if(b.dataset.category){state.category=b.dataset.category;state.limit=18;setView('explore');}else if(b.dataset.journey)openJourney(b.dataset.journey);else if(b.dataset.saved){state.saved=b.dataset.saved;renderSaved();}else if(b.hasAttribute('data-reset'))clearFilters();else if(b.dataset.removeFilter){const k=b.dataset.removeFilter;state[k]='';$('#'+k+'-filter').value='';renderExplore();}else if(b.dataset.copy)copyLink(b.dataset.copy);else if(b.dataset.print)printArticles([byId.get(b.dataset.print)],'実践ガイド');else if(b.dataset.quick){clearFilters();if(b.dataset.quick==='free'){state.cost='無料';$('#cost-filter').value='無料';}if(b.dataset.quick==='short'){state.time='5分';$('#time-filter').value='5分';}if(b.dataset.quick==='urgent')state.category='emergency';renderExplore();$('#explore-panel').scrollIntoView({block:'start'});}});
$('#search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=e.target.value;state.limit=18;renderExplore();},120);});
['cost','time','evidence','audience','sort'].forEach(k=>$('#'+k+'-filter').addEventListener('change',e=>{state[k]=e.target.value;state.limit=18;renderExplore();}));
$('#filter-toggle').onclick=()=>{const open=$('#filters').classList.toggle('open');$('#filter-toggle').setAttribute('aria-expanded',String(open));};
$('#clear-button').onclick=clearFilters;$('#home-button').onclick=()=>{clearFilters();setView('explore');};$('#all-button').onclick=()=>{state.category='';state.limit=18;setView('explore');};
$('#load-more').onclick=()=>{state.limit+=18;renderExplore();};
$('#cards-button').onclick=()=>{state.layout='cards';$('#cards-button').classList.add('active');$('#rows-button').classList.remove('active');renderExplore();};
$('#rows-button').onclick=()=>{state.layout='rows';$('#rows-button').classList.add('active');$('#cards-button').classList.remove('active');renderExplore();};
['about-button','method-button','editorial-button'].forEach(id=>$('#'+id).onclick=showEditorial);
$('#sources-button').onclick=showSources;$('#credits-button').onclick=showCredits;$('#offline-button').onclick=offlineDownload;
$('#dialog-close').onclick=()=>$('#detail-dialog').close();
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#detail-dialog').addEventListener('close',()=>{currentArticle=null;if(location.hash.startsWith('#guide/'))history.replaceState(null,'',location.pathname+location.search);if(state.view==='saved')renderSaved();});
$('#menu-button').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#sidebar-shade').classList.toggle('open',open);$('#menu-button').setAttribute('aria-expanded',String(open));};$('#sidebar-shade').onclick=closeMenu;
$('#theme-button').onclick=()=>setTheme(document.documentElement.dataset.theme!=='dark');
$('#export-button').onclick=exportNotebook;$('#import-button').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>importNotebook(e.target.files[0]);
$('#print-all-button').onclick=()=>printArticles(DATA.articles,'全編');$('#print-saved-button').onclick=()=>printArticles(notebook[state.saved].map(id=>byId.get(id)).filter(Boolean),'マイリスト');
document.addEventListener('keydown',e=>{if(e.key==='/'&&!$('#detail-dialog').open&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();setView('explore',false);$('#search').focus();}if(e.key==='Escape')closeMenu();});
window.addEventListener('hashchange',()=>{const id=location.hash.replace('#guide/','');if(location.hash.startsWith('#guide/')&&byId.has(id))openArticle(id,false);});
$('#search-icon').innerHTML=icon('search');$('#cards-button').innerHTML=icon('grid');$('#rows-button').innerHTML=icon('rows');$('#about-button').innerHTML=icon('info');$('#menu-button').innerHTML=icon('menu');$('#dialog-close').innerHTML=icon('close');
let dark=false;try{dark=localStorage.getItem('kurashi-theme')==='dark';}catch{}setTheme(dark);buildSidebar();updateCounts();setView('explore',false);
if(location.hash.startsWith('#guide/'))openArticle(location.hash.slice(7),false);
