/* Interest-based selection and share cards. No personal data leaves this page. */
const starterThemes=[
 {label:'健康を整える',ids:['health','dental','screening','nutrition','exercise','sleep','food']},
 {label:'お金を見直す',ids:['money','tax','pension','banking','insurance','debt','benefits']},
 {label:'働き方を考える',ids:['work','unemployment','retirement','learning','sidework','harassment','business']},
 {label:'家族を支える',ids:['parenting','education','care','aging','relationship','bereavement','endoflife']},
 {label:'日々を快適に',ids:['housing','moving','homecare','mobility','travel','pets','environment','community','documents']},
 {label:'困る前に備える',ids:['disaster','emergency','climate','consumer','digital','fraud','healthcare','medicine','mental','chronic','accessibility']}
];
let starterResults=[];
function openStarter(){currentArticle=null;showDialog('暮らしの点検',`<div class="prose"><span class="eyebrow">いまの関心から、はじめよう。</span><h2>あなたの、最初の一歩。</h2><p>気になるテーマと使える時間を選ぶだけ。条件に合う記事を最大12件、編集上の優先度とテーマの偏りを考慮して並べます。診断や受給資格の判定ではありません。</p><form id="starter-form"><fieldset class="starter-themes"><legend>気になること（複数選択可）</legend>${starterThemes.map((t,i)=>`<label><input type="checkbox" name="theme" value="${i}"><span>${t.label}</span></label>`).join('')}</fieldset><div class="starter-settings"><label>取りかかる時間<select name="minutes"><option value="">指定しない</option><option value="5分">5分</option><option value="15分">15分以内</option><option value="30分">30分以内</option></select></label><label>費用<select name="cost"><option value="">指定しない</option><option value="無料">まずは無料で</option></select></label></div><p class="checked-note">選択内容は送信・保存されません。該当する記事がなければ条件を広げてください。</p><button class="outline-button starter-submit" type="submit">一歩を見つける →</button></form><div id="starter-results" aria-live="polite"></div></div>`);$('#starter-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),selected=form.getAll('theme').map(Number),allowed=new Set((selected.length?selected:starterThemes.map((_,i)=>i)).flatMap(i=>starterThemes[i].ids)),times=['5分','15分','30分'],limit=times.indexOf(form.get('minutes'));const candidates=DATA.articles.filter(a=>allowed.has(a.category)&&(!form.get('cost')||a.cost===form.get('cost'))&&(limit<0||times.indexOf(a.time)>=0&&times.indexOf(a.time)<=limit)&&!notebook.done.includes(a.id));const buckets=new Map();candidates.sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id)).forEach(a=>{if(!buckets.has(a.category))buckets.set(a.category,[]);buckets.get(a.category).push(a);});starterResults=[];while(starterResults.length<12&&[...buckets.values()].some(b=>b.length))for(const bucket of buckets.values()){if(bucket.length&&starterResults.length<12)starterResults.push(bucket.shift());}$('#starter-results').innerHTML=starterResults.length?`<h3>次の一歩の候補 · ${starterResults.length}件</h3><p>すでに「できた」にした記事は除いています。全部を一度に行う必要はありません。</p><button class="outline-button" data-save-starter>候補をマイリストに保存</button><div class="starter-result-list">${starterResults.map(a=>`<button data-article="${a.id}"><small>${esc(categoryMap.get(a.category).title)} · ${esc(a.time)} · ${esc(a.cost)}</small><strong>${esc(a.title)} ↗</strong></button>`).join('')}</div>`:'<h3>この条件の候補はありません</h3><p>時間・費用の条件を広げるか、別のテーマを選んでみてください。</p>';};}
function showDailyStep(){const candidates=DATA.articles.filter(a=>a.priority===1&&a.time==='5分'&&a.category!=='emergency'&&!notebook.done.includes(a.id));if(!candidates.length){$('#daily-step').hidden=true;return;}const now=new Date(),key=now.getFullYear()*372+now.getMonth()*31+now.getDate(),a=candidates[key%candidates.length];$('#daily-step').innerHTML=`<div><span class="eyebrow">今日の一手</span><button data-article="${a.id}">${esc(a.title)} <span>↗</span></button></div><span class="daily-meta">${esc(categoryMap.get(a.category).title)} · ${esc(a.time)}</span>`;}
function publicArticleUrl(id){return DATA.siteUrl+'guide/'+encodeURIComponent(id)+'.html';}
async function shareArticle(id){const a=byId.get(id);if(!a)return;const payload={title:a.title+'｜くらしの判断帖',text:a.summary,url:publicArticleUrl(id)};try{if(navigator.share)await navigator.share(payload);else await copyLink(id);}catch(e){if(e.name!=='AbortError')await copyLink(id);}}
function wrapCanvas(ctx,text,x,y,maxWidth,lineHeight,maxLines){const chars=Array.from(text);let line='',lines=[];for(const char of chars){if(ctx.measureText(line+char).width>maxWidth&&line){lines.push(line);line=char;}else line+=char;}if(line)lines.push(line);const visible=lines.slice(0,maxLines);if(lines.length>maxLines){let last=visible[visible.length-1];while(ctx.measureText(last+'…').width>maxWidth)last=last.slice(0,-1);visible[visible.length-1]=last+'…';}visible.forEach((s,i)=>ctx.fillText(s,x,y+i*lineHeight));return visible.length*lineHeight;}
async function saveShareCard(id){const a=byId.get(id);if(!a)return;try{await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const c=canvas.getContext('2d');c.fillStyle='#f6f3ea';c.fillRect(0,0,1200,630);c.fillStyle='#183f35';c.fillRect(0,0,18,630);c.fillStyle='#b7ca76';c.beginPath();c.arc(1150,70,170,0,Math.PI*2);c.fill();c.fillStyle='#183f35';c.font='600 25px "Yu Gothic",sans-serif';c.fillText('くらしの判断帖  ／  '+categoryMap.get(a.category).title,64,68);c.font='700 48px "Yu Gothic",sans-serif';wrapCanvas(c,a.title,64,155,1030,67,3);c.fillStyle='#56645b';c.font='25px "Yu Gothic",sans-serif';wrapCanvas(c,a.summary,64,380,1040,38,2);c.fillStyle='#183f35';c.font='600 22px "Yu Gothic",sans-serif';c.fillText(`${a.cost}  ・  ${a.time}  ・  ${a.evidence}`,64,490);c.strokeStyle='#cbd1c4';c.beginPath();c.moveTo(64,524);c.lineTo(1136,524);c.stroke();c.font='20px "Yu Gothic",sans-serif';c.fillText('対象・手順・注意点・原資料は、ウェブ版で。',64,563);c.font='16px "Yu Gothic",sans-serif';c.fillText('確認日 '+a.checked+'  ｜  '+publicArticleUrl(id),64,598);canvas.toBlob(blob=>{if(!blob){toast('画像を作成できませんでした');return;}download('くらしの判断帖-'+id+'.png',blob,'image/png');toast('共有カードを保存しました。投稿時に記事リンクも添えてください。');},'image/png');}catch{toast('画像を作成できませんでした。リンクで共有できます。');}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-starter'))openStarter();else if(b.hasAttribute('data-save-starter')){notebook.bookmarks=[...new Set([...notebook.bookmarks,...starterResults.map(a=>a.id)])];persist();refreshLists();toast('候補をマイリストに保存しました');}else if(b.dataset.share)shareArticle(b.dataset.share);else if(b.dataset.sharecard)saveShareCard(b.dataset.sharecard);});
showDailyStep();
