import fs from 'node:fs';
import path from 'node:path';
import {buildFormats} from './formats.mjs';
import {buildFeature} from './feature.mjs';
const groups=['health','money','life'].map(name=>JSON.parse(fs.readFileSync(`content/${name}.json`,'utf8').replace(/^\uFEFF/,'')));
const config=JSON.parse(fs.readFileSync('site.config.json','utf8'));
const groupNames=['からだと安心','お金と仕事','家族と日々の暮らし'];
const data={...config,groups:groups.map((g,i)=>({title:groupNames[i],ids:g.categories.map(c=>c.id)})),categories:groups.flatMap(g=>g.categories),articles:groups.flatMap(g=>g.articles),journeys:groups.flatMap(g=>g.journeys)};
const readme=fs.readFileSync('README.md','utf8').replace(/\d+テーマ・\d+件の実践ガイド・\d+の場面別行動プラン/g,`${data.categories.length}テーマ・${data.articles.length}件の実践ガイド・${data.journeys.length}の場面別行動プラン`).replace(/\d+テーマ、全文検索/g,`${data.categories.length}テーマ、全文検索`).replace(/\d+章のMarkdown/g,`${data.categories.length}章のMarkdown`);
fs.writeFileSync('README.md',readme);
const template=fs.readFileSync('index.template.html','utf8');
const html=template.replace('/* STYLE */',()=>fs.readFileSync('style.css','utf8')).replace('/* DATA */',()=>JSON.stringify(data).replaceAll('<','\\u003c')).replace('/* APP */',()=>fs.readFileSync('app.js','utf8')+'\n'+fs.readFileSync('enhancements.js','utf8')).replaceAll('/* SITE_URL */',data.siteUrl);
fs.mkdirSync('dist',{recursive:true});fs.writeFileSync('dist/index.html',html);fs.writeFileSync('dist/kurashi-offline.html',html);fs.writeFileSync('dist/guide-data.json',JSON.stringify(data,null,2));
fs.mkdirSync('book',{recursive:true});fs.mkdirSync('docs',{recursive:true});
// Remove only this builder's numbered chapter outputs before regenerating.
for(const filename of fs.readdirSync('book'))if(/^\d{2}-[a-z]+\.md$/.test(filename))fs.unlinkSync(path.join('book',filename));
if(fs.existsSync('docs/share-cover.png'))fs.copyFileSync('docs/share-cover.png','dist/share-cover.png');
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${data.siteUrl}sitemap.xml\n`);
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${data.siteUrl}</loc><lastmod>${data.updated}</lastmod></url></urlset>`);
const articleMarkdown=a=>`<a id="${a.id}"></a>\n\n### ${a.title}\n\n${a.summary}\n\n- **対象の目安：** ${a.audience.join('・')}\n- **費用の目安：** ${a.cost}\n- **${a.category==='emergency'?'平時の準備の時間':'取りかかる時間'}の目安：** ${a.time}\n- **根拠の種類：** ${a.evidence}\n- **内容確認日：** ${a.checked}\n\n**この一歩で、変えられること**\n\n${a.benefit}\n\n**やること、順番に**\n\n${a.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\n**先に確かめたいこと**\n\n${a.cautions.map(s=>`- ${s}`).join('\n')}\n\n**根拠・公式の確認先**\n\n${a.sources.map(s=>`- ${s.publisher}：[${s.title}](${s.url})`).join('\n')}\n\n*記事ID：${a.id}*\n`;
const chapters=data.categories.map((c,i)=>{const filename=`${String(i+1).padStart(2,'0')}-${c.id}.md`;const text=`# ${String(i+1).padStart(2,'0')} ${c.title}\n\n${c.description}\n\n${data.articles.filter(a=>a.category===c.id).map(articleMarkdown).join('\n---\n\n')}`;fs.writeFileSync(path.join('book',filename),text);return {filename,text,c};});
fs.writeFileSync('book/README.md',`# くらしの判断帖・目次\n\n${data.categories.length}章・${data.articles.length}件の実践ガイド。各章を開くと全文を読めます。\n\n[ウェブ版](${data.siteUrl}) ／ [場面別ガイド](../docs/SCENARIOS.md) ／ [編集方針](../docs/EDITORIAL.md)\n\n${chapters.map(x=>`- [${x.c.title}](${x.filename})（${data.articles.filter(a=>a.category===x.c.id).length}件）`).join('\n')}\n`);
const preface=`# くらしの判断帖\n\n## 知って、選んで、少しよく。\n\n日本で暮らす人のための、根拠と手順が見える生活ガイド。${data.categories.length}テーマ、${data.articles.length}件の実践ガイド、${data.journeys.length}の場面別行動プラン。第2版 ${data.updated}。\n\nすべてを実行する必要はありません。いまの自分に必要な一歩を、原資料と照らし合わせて選ぶための本です。\n\n## 読む前に\n\n- 公的機関を中心とした日本の一次資料をもとに、AIを使って調査・編集した第2版です。独立した専門家による全件監修は未実施です。\n- 「公的制度」は制度・公的サービスの公式説明、「公的推奨」は公的機関による推奨、「編集提案」は資料をもとにした整理・行動順です。これらは効果の大小を評価するランクではありません。\n- 費用・所要時間・表示順は編集上の目安です。「無料」は主に調べる・記録する・相談を始める段階を指し、通話料・交通費・購入費・受診費がかかることがあります。「5分」等は取りかかる時間で、手続きの完了時間ではありません。\n- 金額・期限・適用条件は、申請時に原資料と公式窓口で確認してください。自治体、加入保険、家族構成で扱いが異なります。医療・法律・税務の個別判断は専門職に相談してください。\n- 生命の危険がある救急・火災は119、事件・事故の緊急通報は110へ。読むことを優先しないでください。\n- 原資料の自動監視は行っていません。内容確認日以降の変更に注意してください。\n\n## 目次\n\n${chapters.map(x=>`- [${x.c.title}](#chapter-${x.c.id})`).join('\n')}\n\n`;
const journeyText=`# 場面から選ぶ\n\n行動の順番は編集提案です。各記事の適用条件・注意点も合わせて読んでください。\n\n${data.journeys.map(j=>`## ${j.title}\n\n${j.description}\n\n${j.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\n### 関連ガイド\n\n${j.articleIds.map(id=>{const a=data.articles.find(x=>x.id===id),c=chapters.find(x=>x.c.id===a.category);return `- [${a.title}](../book/${c.filename}#${id})（${id}）`;}).join('\n')}`).join('\n\n---\n\n')}`;
fs.writeFileSync('GUIDE.md',preface+chapters.map(c=>`<a id="chapter-${c.c.id}"></a>\n\n`+c.text).join('\n\n---\n\n')+'\n\n---\n\n'+journeyText.replace(/\.\.\/book\/[^)#]+#([^)]*)/g,'#$1'));
fs.writeFileSync('docs/SCENARIOS.md',journeyText);
const sources=new Map();for(const a of data.articles)for(const s of a.sources){if(!sources.has(s.url))sources.set(s.url,{...s,ids:[]});sources.get(s.url).ids.push(a.id);}
fs.writeFileSync('docs/SOURCES.md',`# 出典一覧\n\n第2版確認日：${data.updated}。${sources.size}件の原資料。個々の記事の確認日は記事内とデータに記載しています。\n\n${[...sources.values()].sort((a,b)=>a.publisher.localeCompare(b.publisher,'ja')).map(s=>`## ${s.title}\n\n- 発行元：${s.publisher}\n- 原資料：[${s.title}](${s.url})\n- 関連記事：${s.ids.join('、')}`).join('\n\n')}`);
fs.writeFileSync('dist/GUIDE.md',fs.readFileSync('GUIDE.md'));fs.writeFileSync('dist/SOURCES.md',fs.readFileSync('docs/SOURCES.md'));
buildFormats(data);
buildFeature(data);
console.log(JSON.stringify({articles:data.articles.length,categories:data.categories.length,journeys:data.journeys.length,sources:sources.size,htmlBytes:Buffer.byteLength(html),guideCharacters:fs.readFileSync('GUIDE.md','utf8').length}));
