import fs from 'node:fs';
import {deflateRawSync} from 'node:zlib';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const body=(a)=>`<p class="lead">${e(a.summary)}</p><p class="facts">${e(a.cost)} ／ ${a.category==='emergency'?'平時の準備：':''}${e(a.time)} ／ ${e(a.evidence)}</p><p>対象の目安：${a.audience.map(e).join('・')}</p>${a.category==='emergency'?'<aside>生命の危険がある場合は、読むより先に119へ。</aside>':''}<h2>この一歩で、変えられること</h2><p>${e(a.benefit)}</p><h2>やること、順番に。</h2><ol>${a.steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol><h2>先に確かめたいこと</h2><ul>${a.cautions.map(s=>`<li>${e(s)}</li>`).join('')}</ul><h2>根拠・公式の確認先</h2><ul>${a.sources.map(s=>`<li>${e(s.publisher)}：<a href="${e(s.url)}">${e(s.title)}</a></li>`).join('')}</ul><p class="note">内容確認日：${e(a.checked)}。金額・期限・対象要件は利用時に原資料と窓口で確認してください。費用・着手時間は編集上の目安です。AIを使って調査・編集したガイドで、専門家による全件監修は未実施です。</p>`;
const css=`:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f7f7f1;color:#303b36;font:16px/1.9 "Yu Gothic",Meiryo,sans-serif}header,main,footer{max-width:800px;margin:auto;padding:28px}header{border-bottom:1px solid #dce1d6;display:flex;justify-content:space-between;gap:16px}header a,footer a{font-weight:bold}main{padding-top:45px}h1{font-size:34px;line-height:1.6;color:#183f35;margin:12px 0 26px}h2{font-size:20px;margin-top:36px;color:#183f35}a{color:#225644;text-underline-offset:4px;overflow-wrap:anywhere}li{padding:6px 0}.lead{font-size:18px}.kicker,.note{font-size:13px;color:#646f63}.facts,aside{background:#eaf0e7;padding:14px 18px;border-radius:5px}.cta{display:inline-block;background:#183f35;color:#fff;padding:12px 20px;border-radius:6px;text-decoration:none}.previous-next{display:flex;gap:20px;justify-content:space-between;border-top:1px solid #dce1d6;margin-top:36px;padding-top:22px;font-size:14px}.previous-next a{max-width:48%}footer{font-size:12px;border-top:1px solid #dce1d6;margin-top:40px}@media(max-width:600px){header,main,footer{padding:20px}h1{font-size:27px}body{font-size:15px}}`;
function zip(files){const local=[],central=[];let offset=0;const table=Array.from({length:256},(_,i)=>{for(let j=0;j<8;j++)i=i&1?0xedb88320^(i>>>1):i>>>1;return i>>>0;});for(const [name,value] of files){const raw=Buffer.from(value),nameB=Buffer.from(name),method=name==='mimetype'?0:8,packed=method?deflateRawSync(raw):raw;let crc=0xffffffff;for(const b of raw)crc=table[(crc^b)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(method,8);h.writeUInt16LE(0x21,12);h.writeUInt32LE(crc,14);h.writeUInt32LE(packed.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(nameB.length,26);local.push(h,nameB,packed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);h.copy(c,6,4,30);c.writeUInt32LE(offset,42);central.push(c,nameB);offset+=h.length+nameB.length+packed.length;}const end=Buffer.alloc(22),center=Buffer.concat(central);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(center.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,center,end]);}
export function buildFormats(data){
 fs.mkdirSync('dist/guide',{recursive:true});
 const categories=new Map(data.categories.map(c=>[c.id,c]));
 for(const a of data.articles){const index=data.articles.indexOf(a),prev=data.articles[index-1],next=data.articles[index+1],url=data.siteUrl+'guide/'+a.id+'.html';const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(a.title)}｜くらしの判断帖</title><meta name="description" content="${e(a.summary)}"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:locale" content="ja_JP"><meta property="og:title" content="${e(a.title)}｜くらしの判断帖"><meta property="og:description" content="${e(a.summary)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${data.siteUrl}share-cover.png"><meta name="twitter:card" content="summary_large_image"><style>${css}</style></head><body><header><a href="../">くらしの判断帖</a><a href="../#guide/${a.id}">検索・保存機能で読む →</a></header><main><p class="kicker">${e(categories.get(a.category).title)} ／ ${a.id}</p><h1>${e(a.title)}</h1>${body(a)}<p><a class="cta" href="../#guide/${a.id}">あとで読む・自分用メモ・共有カード →</a></p><nav class="previous-next">${prev?`<a href="${prev.id}.html">← ${e(prev.title)}</a>`:'<span></span>'}${next?`<a href="${next.id}.html">${e(next.title)} →</a>`:''}</nav></main><footer><p>知らないと損する、日本の暮らし。｜くらしの判断帖</p><p>本文 CC BY 4.0 · 企画 Gerry · <a href="${data.repository}">GitHubで読む・訂正を提案する</a></p></footer></body></html>`;fs.writeFileSync(`dist/guide/${a.id}.html`,html);}
 fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${data.siteUrl}</loc><lastmod>${data.updated}</lastmod></url>${data.articles.map(a=>`<url><loc>${data.siteUrl}guide/${a.id}.html</loc><lastmod>${a.checked}</lastmod></url>`).join('')}</urlset>`);
 const xhtml=(title,content)=>`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="ja" lang="ja"><head><title>${e(title)}</title><link rel="stylesheet" href="style.css"/></head><body>${content}</body></html>`;
 const files=[['mimetype','application/epub+zip'],['META-INF/container.xml','<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'],['EPUB/style.css',css]];
 files.push(['EPUB/start.xhtml',xhtml(data.title,`<h1>くらしの判断帖</h1><p>知らないと損する、日本の暮らし。</p><p>${data.categories.length}章・${data.articles.length}件の日本語実践ガイド。</p><p>第2版 ${data.updated}。AIで調査・編集したガイドです。独立した専門家による全件監修は未実施です。制度の金額・対象・期限は利用時に原資料と窓口で確認してください。</p><p>公的制度・公的推奨・編集提案を区別します。費用と時間は取りかかる段階の目安です。全員に同じ効果や適用を保証するものではありません。</p><p>生命の危険がある救急・火災は119、事件・事故の緊急通報は110へ。読むことを優先しないでください。</p><p>本文 CC BY 4.0。企画 Gerry。原資料は各発行元に帰属します。</p><p>生活を費用・便益・根拠から考える構成は <a href="https://github.com/eternity4719/HowToLiveBetter">HowToLiveBetter</a> に着想を得ています。本文は日本の原資料から独自に執筆しています。</p><p><a href="${data.siteUrl}">検索・マイリスト機能のあるウェブ版</a></p>`)]);
 files.push(['EPUB/journeys.xhtml',xhtml('場面から選ぶ',`<h1>場面から選ぶ</h1><p>行動順は編集提案です。各記事の対象と注意点も確認してください。</p>${data.journeys.map(j=>`<section><h2>${e(j.title)}</h2><p>${e(j.description)}</p><ol>${j.steps.map(t=>`<li>${e(t)}</li>`).join('')}</ol><ul>${j.articleIds.map(id=>{const a=data.articles.find(x=>x.id===id);return `<li><a href="${a.category}.xhtml#${a.id}">${e(a.title)}</a></li>`;}).join('')}</ul></section>`).join('')}`)]);
 files.push(['EPUB/nav.xhtml',xhtml('目次',`<nav epub:type="toc" id="toc"><h1>目次</h1><ol><li><a href="start.xhtml">読む前に</a></li><li><a href="journeys.xhtml">場面から選ぶ</a></li>${data.categories.map((c,i)=>`<li><a href="${c.id}.xhtml">${i+1} ${e(c.title)}</a><ol>${data.articles.filter(a=>a.category===c.id).map(a=>`<li><a href="${c.id}.xhtml#${a.id}">${e(a.title)}</a></li>`).join('')}</ol></li>`).join('')}</ol></nav>`)]);
 for(const c of data.categories)files.push([`EPUB/${c.id}.xhtml`,xhtml(c.title,`<h1>${e(c.title)}</h1><p>${e(c.description)}</p>${data.articles.filter(a=>a.category===c.id).map(a=>`<section id="${a.id}"><h1>${e(a.title)}</h1>${body(a)}</section>`).join('')}`)]);
 files.push(['EPUB/package.opf',`<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">${data.siteUrl}edition/${data.version}</dc:identifier><dc:title>くらしの判断帖 — 知らないと損する、日本の暮らし。</dc:title><dc:language>ja</dc:language><dc:creator>Gerry</dc:creator><dc:rights>CC BY 4.0</dc:rights><meta property="dcterms:modified">${data.updated}T00:00:00Z</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="style" href="style.css" media-type="text/css"/><item id="start" href="start.xhtml" media-type="application/xhtml+xml"/><item id="journeys" href="journeys.xhtml" media-type="application/xhtml+xml"/>${data.categories.map(c=>`<item id="c-${c.id}" href="${c.id}.xhtml" media-type="application/xhtml+xml"/>`).join('')}</manifest><spine><itemref idref="start"/><itemref idref="nav"/><itemref idref="journeys"/>${data.categories.map(c=>`<itemref idref="c-${c.id}"/>`).join('')}</spine></package>`]);
 fs.writeFileSync('dist/kurashi.epub',zip(files));
}
export {zip};
